name: design_sys_ciy
description: Flutter design system package that contains themed components, colors pallete
version: 0.0.1
homepage: https://github.com/camiloibarrayepes/design_system_ciy

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true